import fs from 'fs';

export const baseFormatCell = (value, sheeTitle, columnTitle) => value;

export const translationsJsonToFile = (transJson, constName, filename) => {
    let file =
`
/**
 FILE GENERATED BY I18n Sheet Locales
 PLEASE DO NOT MODIFY

*/
`;
    file += '\n\r';
    file += `const ${constName} = ${JSON.stringify(transJson,undefined, 2)}`;
    file += ';\n\r';
    file += `export default ${constName};`;

    fs.writeFileSync(filename, file);
};


export const rowsToLangs = (rows, keyID, langsIds) => {
    // console.log(rows);
    // console.log(keyID);
    // console.log(langsIds);
    let dicts = {};
    langsIds.forEach((id) => {
        dicts[id] = {};
    });

    rows.forEach((item) => {
        langsIds.forEach((dictId) => {
            // console.log('dictId', dictId);
            // console.log('item[dictId]', item[dictId]);
            // console.log('item[keyID]', item[keyID]);
            dicts[dictId] = {
                ...dicts[dictId],
                [item[keyID]]: item[dictId] || undefined,
            };
        });
    });
    return dicts;
};

